apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-input-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "microk8s-hostpath"
  resources:
    requests:
      storage: 5Gi